### ISSUE TITLE
No need to require Account Id when connecting to Nylas

### ISSUE THREAD

**Issue by robtesch** [lanlin/nylas-php#1]
Hi there,

Thanks for the package and the overhaul. It is my understanding that we do not actually need the account ID to connect to nylas, and as such it should not be a "required" field to fire up a Nylas/Client.

Any chance you can remove this requirement?

**Comment by lanlin** [comment]
Aha, only "client_id" & "client_secret" are required, other fields are optional

```shell
use Nylas\Client;

$options =
[
    'debug'         => true,
    'log_file'      => dirname(__FILE__) . '/test.log',
    'account_id'    => 'your account id',
    'access_token'  => 'your access token',
    'client_id'     => 'your client id',        // required
    'client_secret' => 'your client secret'     // required
];

$nylas = new Client($options);
```
