### ISSUE TITLE
Can't add 'reply_to_message_id' when addDraft

### ISSUE THREAD

**Issue by YLoveX** [lanlin/nylas-php#14]
Hello @lanlin,

For **public function addDraft(array $params)** has a baseRules which doesn't have **reply_to_message_id**, when I call it will cause crash.

It would be nice if add this.

Thank you.

![Screen Shot 2020-06-22 at 6 10 07 PM](https://user-images.githubusercontent.com/12166908/85275936-a0e92100-b4b3-11ea-91a0-8c7542bbd016.png)

**Comment by lanlin** [comment]
@YLoveX Wait a minute

**Comment by lanlin** [comment]
@YLoveX https://github.com/lanlin/nylas-php/releases/tag/4.0.5

**Comment by YLoveX** [comment]
@lanlin ,

Thank you.
