### ISSUE TITLE
how can use Webhook?

### ISSUE THREAD

**Issue by ebrahimpleite** [lanlin/nylas-php#18]
any examples?

**Comment by ebrahimpleite** [comment]
any examples?

**Comment by lanlin** [comment]
@ebrahimpleite here's the  [Nylas Webhook API Docs](https://docs.nylas.com/reference#webhooks)

1. create webhook from the Nylas dashboard or just call method below

```php
$nylas->Webhooks()->Webhook()->createWebhook($data);
```

2. Nylas will send a challenge string to your webhook after it created or every time it reactivated, this challenge string must be responded to Nylas immediately. you can do it like this

```php
if (!empty($_GET['challenge']))
{
    $nylas->Webhooks()->Webhook()->echoChallenge();
}

$data = $nylas->Webhooks()->Webhook()->getNotification();
```

**Comment by ebrahimpleite** [comment]
Fatal error: Uncaught Nylas\Exceptions\NylasException: not a valid nylas request in /Applications/XAMPP/xamppfiles/htdocs/project/vendor/lanlin/nylas-php/src/Webhooks/Webhook.php:79 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/project/nylas/webhook.php(20): Nylas\Webhooks\Webhook->getNotification() #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/etraducoes/vendor/lanlin/nylas-php/src/Webhooks/Webhook.php on line 79

my code:
`<?php

require '../vendor/autoload.php';

use Nylas\Client;

$options = [
    'debug' => false,
    'log_file' => dirname(__FILE__) . '/test.txt', 
    'client_id' => '***',  
    'client_secret' => '***'     
];
$nylas = new Client($options);

if (!empty($_GET['challenge'])) {
    $nylas->Webhooks()->Webhook()->echoChallenge();
}

$data = $nylas->Webhooks()->Webhook()->getNotification();`

**Comment by ebrahimpleite** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Nylas\Webhooks\Webhook::__construct() must be an instance of Nylas\Utilities\Options, array given, called in /Applications/XAMPP/xamppfiles/htdocs/project/nylas/webhook.php on line 12 and defined in /Applications/XAMPP/xamppfiles/htdocs/project/vendor/lanlin/nylas-php/src/Webhooks/Webhook.php:33 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/project/nylas/webhook.php(12): Nylas\Webhooks\Webhook->__construct(Array) #1 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/project/vendor/lanlin/nylas-php/src/Webhooks/Webhook.php on line 33

my code:

```
<?php

require '../vendor/autoload.php';

use Nylas\Webhooks\Webhook;

$options = [
    'client_id' => '',
    'callback_url' => ''
];
$nylas = new Webhook($options);

if (!empty($_GET['challenge'])) {
    $nylas->Webhooks()->Webhook()->echoChallenge();
}

$data = $nylas->Webhooks()->Webhook()->getNotification();
```

**Comment by lanlin** [comment]
@ebrahimpleite well... I guess you have not read the nylas-php document yet.

```php
$options = [];   // your options

$nylas = new \Nylas\Client($options);

$nylas->foo()->foo()
...
```
