### ISSUE TITLE
Why is the tracking option always returning 403 Error?

### ISSUE THREAD

**Issue by MilesYM** [lanlin/nylas-php#24]
Hi Lanlin, first, thank you for your awesome sdk. very helpful.

I'm trying to send an email via nylas with tracking options turned on.
I have configured all the webhooks on nylas and I'm still on dev mode.

If I'm sending an email WITHOUT tracking, then it works:
```
        $params = [
            'to' => [
                [
                  'email' => $to,
                  'name' => $name,
                ],
            ],
            'body' => $message,
            'subject' => $subject,
        ];

        return $this->nylas->Messages()->Sending()->sendDirectly($params);
```

However, if I'm enabling tracking it always fail:

```
        $params = [
            'to' => [
                [
                  'email' => $to,
                  'name' => $name,
                ],
            ],
            'tracking' => [
                'links' => false,
                'opens' => true,
                'thread_replies' => true,
            ],
            'body' => $message,
            'subject' => $subject,
        ];

        return $this->nylas->Messages()->Sending()->sendDirectly($params);
```

I'm getting a 403 error with the following message:

> Includes authentication errors, blocked developer applications, and cancelled accounts.

Any idea why is this happening?

Thank you

**Comment by lanlin** [comment]
@MilesYM you're welcome.
![image](https://user-images.githubusercontent.com/3468024/95934222-ecc52a80-0e02-11eb-94b4-fcd9234141c4.png)

the 403 error means forbidden.
see this doc [Enabling Tracking](https://docs.nylas.com/reference#section-enabling-tracking)

![image](https://user-images.githubusercontent.com/3468024/95934517-9dcbc500-0e03-11eb-8509-55b7f7270f76.png)

Here's a note under the code.
I guess it not working under a trial app.

**Comment by MilesYM** [comment]
Got it, thank you for your detailed response.
