### ISSUE TITLE
Stability and maintainability of this package in large scale production environment

### ISSUE THREAD

**Issue by ryantbrown** [lanlin/nylas-php#25]
Hey Lanlin,

It's awesome that you are maintaining a PHP SDK for Nylas, since they do not offer one.  We are getting ready to refactor our Nylas integration and would love to build on top of this, just curious to get your thoughts on the overall stability.

Are you currently using this SDK in any production environments? Would you recommend utilizing the SDK in a large scale SAAS application?

Of course, if we do leverage the SDK, we would be happy to contribute to the project.

Let me know what you think.

**Comment by lanlin** [comment]
@ryantbrown to be honest I write this SDK for the same reason as you. 

They do not offer an SDK for PHP, so I have to write it myself.
I think there may some others who need it like me so I make it opened.

This package aims to follow the latest [Nylas REST API](https://docs.nylas.com/reference).
I just add a validator named [Respect Validation](https://github.com/Respect/Validation) & an HTTP client named [Guzzlehttp](https://github.com/guzzle/guzzle) for these APIs, there's no more magic.

Feel free to test it, and any contributions are welcome!
