### ISSUE TITLE
am I missing a file?

### ISSUE THREAD

**Issue by nuhusky001** [lanlin/nylas-php#28]
local.ERROR: Return value of Nylas\Request\Sync::getStream() must implement interface Psr\Http\Message\ResponseInterface, 

using php 7.4, nylas-php 4.2.2, composer 1.0.x - worked until we upgraded to php 7.4 on Ubuntu 20 LTS

**Comment by lanlin** [comment]
@nuhusky001 try this https://github.com/lanlin/nylas-php/releases/tag/4.2.3
