### ISSUE TITLE
Is there a method for upgrade and downgrade?

### ISSUE THREAD

**Issue by MilesYM** [lanlin/nylas-php#29]
While I have been able to use this SDK for pretty much everything, I have not been able to find the methods for the following calls :

curl -X POST -u YOUR_APP_SECRET https://api.nylas.com/a/YOUR_APP_ID/accounts/ACCOUNT_ID/downgrade
curl -X POST -u YOUR_APP_SECRET https://api.nylas.com/a/YOUR_APP_ID/accounts/ACCOUNT_ID/upgrade

This is something I need to do as per Nylas recommendations:

Workflow 1: Stopped Status Reauth Workflow

With account sync_status webhooks enabled, you can easily re-start sync on any account using the guide below.

Step 1: Restart Sync

    When you get a Stopped Sync status, create automation to immediately restart the customer's sync.  NOTE: We only keep logs for 2 weeks, so it's important we are made aware asap if reauth and troubleshooting do not solve a stopped sync. 
    You can use the code below or read more about it here/

curl -X POST -u YOUR_APP_SECRET https://api.nylas.com/a/YOUR_APP_ID/accounts/ACCOUNT_ID/downgrade
curl -X POST -u YOUR_APP_SECRET https://api.nylas.com/a/YOUR_APP_ID/accounts/ACCOUNT_ID/upgrade

Is this implemented in the SDK?

Thank you for the great support.

Best,

**Comment by lanlin** [comment]
@MilesYM here are the methods, my friend

```php
$nylas->Accounts()->Manage()->cancelAccount()
$nylas->Accounts()->Manage()->reactiveAccount()
$nylas->Accounts()->Manage()->revokeAllTokens($params)
```

![image](https://user-images.githubusercontent.com/3468024/103183900-47ddc800-48f0-11eb-816b-8dd2072cfad6.png)

![image](https://user-images.githubusercontent.com/3468024/103184002-bb7fd500-48f0-11eb-8016-93deb895be7a.png)

**Comment by MilesYM** [comment]
Thank you. You are providing better support than Nylas themselves, who tend to be rather slow at answering questions.

Have a wonderful holiday.
Best,

**Comment by lanlin** [comment]
@MilesYM thanks, have a nice day
