### ISSUE TITLE
Irish and Canadian servers

### ISSUE THREAD

**Issue by olamm2k** [lanlin/nylas-php#30]
Hi. Are there any plans to support the Irish and Canadian servers, please? As per https://docs.nylas.com/docs/data-residency

Ireland: https://ireland.api.nylas.com/
Canada: https://canada.api.nylas.com/

**Comment by lanlin** [comment]
@olamm2k well, give me sometime

**Comment by lanlin** [comment]
@olamm2k try this:
for php >7.4 https://github.com/lanlin/nylas-php/releases/tag/4.2.4
for php >7.3 https://github.com/lanlin/nylas-php/releases/tag/3.7.4

**Comment by olamm2k** [comment]
Thanks, very quick work. I was going to send a pull request, but you beat me to it.
