### ISSUE TITLE
Sokil isocodes

### ISSUE THREAD

**Issue by robtesch** [lanlin/nylas-php#31]
Hi there, the latest update appears to have a dependency on sokil/php-isocodes which is causing all sorts of havoc with composer on my side. Do we need this dependency?

**Comment by lanlin** [comment]
@robtesch there's no dependence named sokil/php-isocodes

![image](https://user-images.githubusercontent.com/3468024/111928491-b9dc3c80-8aee-11eb-80b1-260c70178e4d.png)

**Comment by robtesch** [comment]
Right you are. So bizarre, I ran composer update and saw that it installed this package and updated yours. Since that package is related to localized names of countries and I jumped to the conclusion that this was related to your latest update. Rolling back the update also stopped the composer problems related to that package. Now I've run composer update again and no issues at all. Sorry for the false alarm.
