### ISSUE TITLE
All of the required rules must pass for

### ISSUE THREAD

**Issue by kapdom** [lanlin/nylas-php#32]
Hi. I'm trying to authenticate new user and I have following error:

> All of the required rules must pass for `{ "state": "testing", "login_hint": "test@gmail.com", "redirect_uri": "/", "response_type": "code", "scopes": { "email.read_only", "calendar.read_only", "contacts.read_only" }, ... }

This is my code:

```
$params =
            [
                'state'        => 'testing',
                'login_hint'   => 'test@gmail.com',
                'redirect_uri' => $router->generate('home'),
                'response_type' => 'code',
                'scopes' => ['email.read_only','calendar.read_only','contacts.read_only'],
                'Authorization' => 'fakeSecret',
                'client_id'   => 'fakeClientId',
            ];
        $nylas = new Client($options);
        $nylas->Authentication()->Hosted()->getOAuthAuthorizeUrl($params);
```
When I use CURL:

`        curl -G \
        --url 'https://api.nylas.com/oauth/authorize' \
    -H 'Authorization: Basic fakeAutho' \
    -d 'client_id=fakeClientId' \
    -d 'redirect_uri=http://127.0.0.1' \
    -d 'response_type=code' \
    -d 'scopes=email.read_only,calendar.read_only,contacts.read_only' \
    -d 'login_hint=test@gmail.com' \
    -d 'state=testing'
`
Then I get correct response.
What is wrong? I think I send all necessary params.

**Comment by lanlin** [comment]
@kapdom sorry for the late response, I'll check this

**Comment by lanlin** [comment]
@kapdom the 'Authorization' is not required for this library, & the 'scopes' must be a string split by ','

```php
        $params = [
            'state'         => 'testing',
            'client_id'     => 'fakeClientId',
            'login_hint'    => 'test@gmail.com',
            'redirect_uri'  => 'http://127.0.0.1',
            'response_type' => 'code',
            'scopes'        => 'email.read_only,calendar.read_only,contacts.read_only',
        ];

        $url = $this->client->Authentication()->Hosted()->getOAuthAuthorizeUrl($params);
```

**Comment by kapdom** [comment]
Thank you. But now I have a problem with "native" auth:
For following code:

```
        $nylas = new Client($options);
        $a = $nylas->Authentication()->Native()->postConnectAuthorize([

            'client_id'     => 'fakeId',
            'provider' => 'gmail',
            'name' => 'Test',
            'email_address' => 'fake@gmail.com',
            'scopes' => 'email.folders_and_labels, contacts, calendar, email.modify, email.send, email.drafts, email.metadata',
            'settings' => [
                "google_client_id" => "fakeId.apps.googleusercontent.com",
"google_client_secret" => "fakid",
"google_refresh_token" => "fakeId"
            ]
        ]);
```
Always I have this error: 

> Malformed or missing a required parameter, or your email provider not support this.

But when I provide the same (of course not fake date that I pasted in post) I receive correct "code".

So is there a mistake in my code?

**Comment by lanlin** [comment]
@kapdom er... may I ask a question, you don't know much about PHP, right? 
would you please read the documentation of this library first: https://github.com/lanlin/nylas-php#error--exceptions

```php
"http_errors" => false,   // you closed the HTTP error throw?
```
