### ISSUE TITLE
Support for Conference Sync - Beta

### ISSUE THREAD

**Issue by JacekAndrzejewski** [lanlin/nylas-php#35]
Hi, I wanted to create Google Meet meetings with the API as described [in docs](https://developer.nylas.com/docs/connectivity/calendar/conference-sync-beta/#create-a-conference-event), but as I can see right now it's not supported by the library. Are you planning to update to support that? Or is it possible right now, but I didn't find the right thing?

**Comment by lanlin** [comment]
@JacekAndrzejewski sorry, I think it could be better to add support to this when it is truly released.
![image](https://user-images.githubusercontent.com/3468024/125217782-1492e180-e2f4-11eb-926e-16f7c76d4509.png)
