### ISSUE TITLE
Make Sending::getMessgeRules() public?

### ISSUE THREAD

**Issue by nurikabe** [lanlin/nylas-php#38]
Would it be possible to make `Sending::getMessageRules()` public? I'd like to sanity check a message before calling `sendDirectly()`.

Could `getMessageRules()` be static?

**Comment by lanlin** [comment]
@nurikabe the PHP ReflectionMethod can make sense, see here https://www.php.net/manual/en/class.reflectionmethod.php

```php
$method = new ReflectionMethod($object, $method);
$method->setAccessible(true);
$method->invoke($object);
```
