### ISSUE TITLE
The requested item doesn't exist

### ISSUE THREAD

**Issue by laukit123** [lanlin/nylas-php#4]
Hello,
When I call the message API with messageID I got error "The requested item doesn't exist".
When I call same directly nylas API using Curl I got response successfully.
Thank You
Laukit

**Comment by lanlin** [comment]
@laukit123 more detail, please. which method and how you call it?

if you mean the `getMessage($messageId)` method, I have tested it again, works fine.

"The requested item doesn't exist" means the Nylas API response a 404 status code, that said the id may not exists.

**Comment by laukit123** [comment]
I am call message API getMessage(('awcss1sbzcvr0249de3bjk8z3');
This is return error => true and message => 'The requested item doesn't exist'.
'awcss1sbzcvr0249de3bjk8z3' This is the messageid.
Please check attached response file.
[messageResponse.txt](https://github.com/lanlin/nylas-php/files/3385158/messageResponse.txt)

**Comment by lanlin** [comment]
@laukit123 sorry, I am pretty sure this method is ok.

please try this, with your own access token

```shell
curl -X GET 'https://api.nylas.com/messages/awcss1sbzcvr0249de3bjk8z3' -H 'Authorization: ACCESS_TOKEN_HERE' -H 'cache-control: no-cache'
```

I think there's no message for `awcss1sbzcvr0249de3bjk8z3` id in your current account.

maybe it just in another account.

**Comment by laukit123** [comment]
Hello,
This is the response of above curl command:
{
    "account_id": "8ri9c63h75zfrn55dy7abubfl",
    "bcc": [],
    "body": "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"></head><body>Boa tarde,<div><br></div><div><div>Serve o presente para enviar dados para o pedido da baixada definita da obra mencionada em assunto:</div></div><div><br></div><div>Obra do. Covelo- Moradia Esquerda:</div><div>Rua Costa Cabral, Uni\u00e3o das freguesias de Vila Nova de Famalic\u00e3o e Calend\u00e1rio, Vila Nova de Famalic\u00e3o.</div><div>Maria Carolina Gomes de Carvalho cc 179727770 e Maria Jos\u00e9 Gomes de Carvalho cc 157244938</div><div><br></div><div>Em anexo os cart\u00f5es de cidad\u00e3o das 2 irm\u00e3s e a licen\u00e7a de constru\u00e7\u00e3o.</div><div><object type=\"application/x-apple-msg-attachment\" data=\"cid:6CBEA646-68B4-4E5B-8C1A-19762DAFE25A@home\" apple-inline=\"yes\" style=\"background-color: rgb(254,254,254); -apple-color-filter: none\" id=\"E325C718-9660-498F-8D52-1201DA73235E\" height=\"517\" width=\"730\" apple-width=\"yes\" apple-height=\"yes\"></object></div><div><br></div><div id=\"AppleMailSignature\">\n<span style=\"font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(11, 83, 148); color: rgb(11, 83, 148); font-family: -apple-system, BlinkMacSystemFont, sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);\">Com os melhores cumprimentos / best regards,</span><br style=\"caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;\"><table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"480\" style=\"caret-color: rgb(0, 0, 0); letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: -webkit-standard; background-color: rgb(255, 255, 255); max-width: 480px; width: 460px;\"><tbody><tr><td align=\"left\" valign=\"top\" width=\"300\" style=\"caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr class=\"signRow\"><td style=\"font-family: &quot;Century Gothic&quot;, Arial, sans-serif; line-height: 26px; padding: 0px;\">Eng.\u00ba Ricardo&nbsp;<strong>Silva</strong></td></tr><tr class=\"signRow\"><td style=\"font-family: arial; font-size: 12px; line-height: 18px;\">Dire\u00e7\u00e3o Geral<br></td></tr><tr class=\"signRow\"><td style=\"word-wrap: break-word; font-size: 0px; padding-top: 5px; padding-bottom: 5px;\"><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\" style=\"font-size: 1px; margin: 0px auto; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(44, 130, 201); width: 256.375px;\"><tbody><tr><td style=\"height: 0px; line-height: 0;\">&nbsp;</td></tr></tbody></table></td></tr><tr class=\"signRow\"><td style=\"font-family: arial; font-size: 12px; line-height: 18px; vertical-align: middle;\">+351 912 337 899<br></td></tr><tr class=\"signRow\"><td style=\"font-family: arial; font-size: 12px; line-height: 18px;\">&nbsp;<a href=\"http://joph.pt/\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: inherit;\">www.joph.pt</a></td></tr></tbody></table></td><td align=\"left\" valign=\"top\" width=\"180\" style=\"caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; padding: 10px;\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td align=\"center\" valign=\"top\"><a href=\"http://joph.pt/\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: inherit;\"><span class=\"Apple-string-attachment\"><span class=\"Apple-string-attachment\"><span class=\"Apple-string-attachment\"><span class=\"Apple-string-attachment\"><span class=\"Apple-string-attachment\"></span></span></span></span></span></a></td></tr></tbody></table></td></tr></tbody></table><span class=\"Apple-string-attachment\"><object height=\"200\" width=\"142\" type=\"application/x-apple-msg-attachment\" data=\"cid:D5EE8D06-14C1-42CA-B71A-4B995DE10505@lan\" apple-inline=\"yes\" id=\"5DC8960F-ED79-49E4-82CE-073ABB206E24\" apple-width=\"yes\" apple-height=\"yes\"></object></span><span class=\"Apple-string-attachment\" style=\"caret-color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 0);\"><br></span><span class=\"Apple-string-attachment\" style=\"caret-color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 0);\"><br><br><br><br><br><br><br><br></span><div style=\"caret-color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 0); text-decoration: none; font-family: Helvetica; font-size: 12px; text-align: start;\"><br class=\"Apple-interchange-newline\"><br></div><div style=\"caret-color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 0); text-decoration: none; font-family: Helvetica; font-size: 12px; text-align: start;\"><br class=\"Apple-interchange-newline\"><br></div><br class=\"Apple-interchange-newline\" style=\"caret-color: rgb(0, 0, 0); font-family: -webkit-standard; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: -webkit-center; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; color: rgb(0, 0, 0); text-decoration: underline;\">\n</div>\n<br></body></html>",
    "cc": [
        {
            "email": "jose.rosinha@joph.pt",
            "name": "Rosinha"
        }
    ],
    "date": 1561972389,
    "events": [],
    "files": [
        {
            "content_disposition": "inline",
            "content_id": "6CBEA646-68B4-4E5B-8C1A-19762DAFE25A@home",
            "content_type": "application/pdf",
            "filename": "Licenc\u0327a Maria Carolina e Maria Jose\u0301 Carvalho.pdf",
            "id": "91807y4yhiydeuqkl540p6eeg",
            "size": 59386
        },
        {
            "content_disposition": "inline",
            "content_id": "D5EE8D06-14C1-42CA-B71A-4B995DE10505@lan",
            "content_type": "image/png",
            "filename": "img-5bbcaa6479ae6.png",
            "id": "9qzvm3b4ij8c2jm8v3h0tn4hb",
            "size": 3842
        },
        {
            "content_disposition": "attachment",
            "content_type": "application/pdf",
            "filename": "Cc-Maria Jos\u00e9.pdf",
            "id": "dy3gygp5x0juybr07e46a5j7w",
            "size": 352730
        },
        {
            "content_disposition": "attachment",
            "content_type": "application/pdf",
            "filename": "Cc. Maria Carolina.pdf",
            "id": "dptqni5f8a6le6fstah6lv4cq",
            "size": 351636
        }
    ],
    "from": [
        {
            "email": "ricardo.silva@joph.pt",
            "name": "Ricardo Silva"
        }
    ],
    "id": "awcss1sbzcvr0249de3bjk8z3",
    "labels": [
        {
            "display_name": "Todo o correio",
            "id": "58zfc6plppb4g2q40rve6f216",
            "name": "all"
        },
        {
            "display_name": "Correio enviado",
            "id": "40mavnaw3w5ikbodhc7sf1h5x",
            "name": "sent"
        }
    ],
    "object": "message",
    "reply_to": [],
    "snippet": "Boa tarde, Serve o presente para enviar dados para o pedido da baixada definita da obra mencionada em assunto: Obra do. Covelo- Moradia Esquerda: Rua Costa Cabral, Uni\u00e3o das freguesias de Vil",
    "starred": false,
    "subject": "Baixada definitiva - Obra do Covelo (Esquerda)",
    "thread_id": "3uauc65xqwecq8iu4198ptlwb",
    "to": [
        {
            "email": "geral.hurlec@gmail.com",
            "name": "HURLEC unipessoal,lda"
        }
    ],
    "unread": false
}

**Comment by lanlin** [comment]
@laukit123 sorry, I can't find anything help

may you check your access token set for `\Nylas\Client()` again, please.

![image](https://user-images.githubusercontent.com/3468024/61111221-aa07fa80-a4bb-11e9-9dba-0c244c5938e3.png)

does it really same as the token that used in the curl command?
please try again, check your account and access token.

**Comment by laukit123** [comment]
I dump the request parameter and all are good.
But just for this message I got this error message for other this is working fine.

**Comment by lanlin** [comment]
@laukit123 ok, so the best way is to contact Nylas for help, good luck.
