### ISSUE TITLE
Free/Busy API

### ISSUE THREAD

**Issue by olamm2k** [lanlin/nylas-php#40]
Hi,

We need to use the Free/Busy API from Nylas. I have created a Pull Request. You can check the documentation here: https://developer.nylas.com/docs/connectivity/calendar/calendar-availability/#free/busy. Could you take a look, please?

PR: https://github.com/lanlin/nylas-php/pull/39

Regards,
Oliver

**Comment by lanlin** [comment]
@olamm2k thanks for your contribution
