### ISSUE TITLE
No Native Auth example in docs

### ISSUE THREAD

**Issue by MatthewLoffredo** [lanlin/nylas-php#44]
I'm implementing this on a web app with it's own auth system that will be connected to nylas, and I think it would be helpful to include a native auth example (including the detectProvider function) in the docs.

**Comment by axis80** [comment]
@MatthewLoffredo I am also working on implementing native auth at the moment.  I'll be glad to share my notes here as I work out the implementation through trial and error.  If you want to do the same, then perhaps we could help each other out and come up with an example for the docs in the process.

**Comment by lanlin** [comment]
Native Authentication: https://developer.nylas.com/docs/the-basics/authentication/native-authentication/

sorry guys,  I don't have much time to write the example for each method, but all methods' comment has a link to their specific API document.

![image](https://user-images.githubusercontent.com/3468024/156952405-dcb68f22-6fbd-478c-920f-88ac2eb261d6.png)
