### ISSUE TITLE
Add support for Nylas Scheduler API

### ISSUE THREAD

**Issue by MatthewLoffredo** [lanlin/nylas-php#46]
It would be very useful to support the Nylas Scheduler API (https://developer.nylas.com/docs/api/scheduler/#overview), which allows imbedding custom scheduling pages/flows into an app.

**Comment by lanlin** [comment]
it will be considered in the next time update(since API 2.4 released to the latest changes)

**Comment by MatthewLoffredo** [comment]
I've implemented the Scheduler API in my own fork of the repo, if anyone wants to use it until the next release: https://github.com/MatthewLoffredo/nylas-php

**Comment by lanlin** [comment]
Scheduler https://github.com/lanlin/nylas-php/releases/tag/5.3.0
