### ISSUE TITLE
$client->Files()->File()->uploadFile() does not return uploaded file object

### ISSUE THREAD

**Issue by gvanto** [lanlin/nylas-php#5]
```
$params = [
            'contents' => $tmpFilePath,
            'filename' => basename($tmpFilePath),
        ];

$resp = $this->client->Files()->File()->uploadFile($params);
```

But all I get back in response is the same $params array which was passed in.

I've checked the nylas account logs and a successful (Http Response = 200) API call was made to the API ...

Thanks

**Comment by lanlin** [comment]
@gvanto try this new release https://github.com/lanlin/nylas-php/releases/tag/3.5.1

**Comment by gvanto** [comment]
Thanks so much @lanlin is working now 👍
