### ISSUE TITLE
client initialization issue when no log file given

### ISSUE THREAD

**Issue by Grummfy** [lanlin/nylas-php#6]
hello,
when we don't give any 'log_file' value, the default one is null

`$this->setLogFile($options['log_file'] ?? null);`

but setLogFile require a string

`Argument 1 passed to Nylas\Utilities\Options::setLogFile() must be of the type string, null given, called in /var/www/stellar/vendor/lanlin/nylas-php/src/Utilities/Options.php on line 88`

**Comment by lanlin** [comment]
fixed https://github.com/lanlin/nylas-php/releases/tag/4.0.2

**Comment by Grummfy** [comment]
thanks
