### ISSUE TITLE
use php-fig/log instead of a filepath for log

### ISSUE THREAD

**Issue by Grummfy** [lanlin/nylas-php#7]
Hello,
instead of a file, I think that using https://github.com/php-fig/log could be better. It allow people to inject it inside they framework logger instead of creating a file....

thanks

**Comment by lanlin** [comment]
@Grummfy thanks for your advice, just wait for a while

**Comment by lanlin** [comment]
@Grummfy https://github.com/lanlin/nylas-php/releases/tag/4.0.2

**Comment by Grummfy** [comment]
that was fast!
